from enum import StrEnum


class RunMode(StrEnum):
    LIVE = "LIVE"
    REPLAY = "REPLAY"


class RunStatus(StrEnum):
    CREATED = "CREATED"
    PENDING = "PENDING"
    WAITING_FOR_EXECUTION = "WAITING_FOR_EXECUTION"
    RUNNING = "RUNNING"
    VERIFYING = "VERIFYING"
    READY_FOR_REPORT = "READY_FOR_REPORT"
    PAUSED = "PAUSED"
    INTERRUPTED = "INTERRUPTED"
    BLOCKED = "BLOCKED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class WorkflowPhase(StrEnum):
    CREATED = "CREATED"
    PLAN = "PLAN"
    COLLECT = "COLLECT"
    ANALYZE = "ANALYZE"
    VERIFY = "VERIFY"
    REPORT = "REPORT"
    REVIEW = "REVIEW"
    COMPLETED = "COMPLETED"


class ExecutionStepStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    INTERRUPTED = "INTERRUPTED"
    CANCELLED = "CANCELLED"


class ExternalCallStatus(StrEnum):
    SUCCESS = "SUCCESS"
    TIMEOUT = "TIMEOUT"
    PROVIDER_ERROR = "PROVIDER_ERROR"
    RATE_LIMITED = "RATE_LIMITED"
    INVALID_RESPONSE = "INVALID_RESPONSE"
    SECURITY_BLOCKED = "SECURITY_BLOCKED"
    CANCELLED = "CANCELLED"


class StepType(StrEnum):
    PLANNING = "PLANNING"
    RESEARCH = "RESEARCH"
    SEARCH = "SEARCH"
    FETCH = "FETCH"
    EXTRACTION = "EXTRACTION"
    ANALYSIS = "ANALYSIS"
    VALIDATION = "VALIDATION"
    REPORTING = "REPORTING"
    REVIEW = "REVIEW"
    OTHER = "OTHER"


class AgentRole(StrEnum):
    SUPERVISOR = "SUPERVISOR"
    RESEARCHER = "RESEARCHER"
    ANALYST = "ANALYST"
    VERIFIER = "VERIFIER"
    WRITER = "WRITER"
    HARNESS = "HARNESS"


class ResearchTaskStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class SourceType(StrEnum):
    OFFICIAL_REPORT = "OFFICIAL_REPORT"
    OFFICIAL_STATEMENT = "OFFICIAL_STATEMENT"
    NEWS = "NEWS"
    TECHNICAL_ANALYSIS = "TECHNICAL_ANALYSIS"
    PUBLIC_DATA = "PUBLIC_DATA"
    WEB_PAGE = "WEB_PAGE"
    PDF_REPORT = "PDF_REPORT"
    OTHER = "OTHER"


class ParseStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    FETCHED = "FETCHED"
    PARSED = "PARSED"
    PARTIALLY_PARSED = "PARTIALLY_PARSED"
    UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE"
    UNSUPPORTED_SCANNED_PDF = "UNSUPPORTED_SCANNED_PDF"
    INSUFFICIENT_TEXT_LAYER = "INSUFFICIENT_TEXT_LAYER"
    EMPTY_CONTENT = "EMPTY_CONTENT"
    CORRUPT_DOCUMENT = "CORRUPT_DOCUMENT"
    ENCRYPTED_PDF = "ENCRYPTED_PDF"
    FETCH_FAILED = "FETCH_FAILED"
    PARSE_FAILED = "PARSE_FAILED"


class ArtifactType(StrEnum):
    HTML_NORMALIZED_TEXT = "HTML_NORMALIZED_TEXT"
    PLAIN_TEXT = "PLAIN_TEXT"
    PDF_PAGE_TEXT = "PDF_PAGE_TEXT"
    STRUCTURED_METADATA = "STRUCTURED_METADATA"


class LocatorType(StrEnum):
    TEXT_RANGE = "TEXT_RANGE"
    PDF_TEXT_RANGE = "PDF_TEXT_RANGE"


class ClaimType(StrEnum):
    STATEMENT = "STATEMENT"
    INSTITUTIONAL_ACTION = "INSTITUTIONAL_ACTION"
    EVENT_FACT = "EVENT_FACT"
    QUANTITATIVE = "QUANTITATIVE"
    CAUSAL = "CAUSAL"
    IMPACT = "IMPACT"
    ATTRIBUTION = "ATTRIBUTION"
    ANALYTIC_INFERENCE = "ANALYTIC_INFERENCE"


class ClaimImportance(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ValidationStatus(StrEnum):
    PENDING = "PENDING"
    REQUIRES_RESEARCH = "REQUIRES_RESEARCH"
    REJECTED = "REJECTED"
    VERIFIED = "VERIFIED"
    PROBABLE = "PROBABLE"
    DISPUTED = "DISPUTED"
    UNVERIFIED = "UNVERIFIED"


class RelationStance(StrEnum):
    SUPPORTS = "SUPPORTS"
    CONTRADICTS = "CONTRADICTS"
    CONTEXT = "CONTEXT"


class EntailmentStatus(StrEnum):
    PENDING = "PENDING"
    ENTAILED = "ENTAILED"
    NOT_ENTAILED = "NOT_ENTAILED"
    CONTRADICTED = "CONTRADICTED"
    UNCERTAIN = "UNCERTAIN"


class SemanticJudgmentStatus(StrEnum):
    ENTAILS = "ENTAILS"
    PARTIALLY_SUPPORTS = "PARTIALLY_SUPPORTS"
    CONTRADICTS = "CONTRADICTS"
    NOT_RELEVANT = "NOT_RELEVANT"
    UNCERTAIN = "UNCERTAIN"


class ConflictType(StrEnum):
    QUANTITATIVE = "QUANTITATIVE"
    TEMPORAL = "TEMPORAL"
    ATTRIBUTION = "ATTRIBUTION"
    CAUSAL = "CAUSAL"
    SCOPE = "SCOPE"
    DEFINITION = "DEFINITION"
    OTHER = "OTHER"


class ConflictSeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    BLOCKING = "BLOCKING"


class ConflictStatus(StrEnum):
    OPEN = "OPEN"
    REQUIRES_RESEARCH = "REQUIRES_RESEARCH"
    RESOLVED = "RESOLVED"
    ACCEPTED_UNRESOLVED = "ACCEPTED_UNRESOLVED"


class ConflictResolutionStatus(StrEnum):
    UNRESOLVED = "UNRESOLVED"
    RESOLVED_WITH_SCOPE = "RESOLVED_WITH_SCOPE"
    RESOLVED_WITH_TIME = "RESOLVED_WITH_TIME"
    RESOLVED_WITH_DEFINITION = "RESOLVED_WITH_DEFINITION"
    NO_CONFLICT = "NO_CONFLICT"


class ResearchGapType(StrEnum):
    EVIDENCE_GAP = "EVIDENCE_GAP"
    UNREADABLE_SOURCE = "UNREADABLE_SOURCE"
    SOURCE_CONFLICT = "SOURCE_CONFLICT"
    MISSING_PRIMARY_SOURCE = "MISSING_PRIMARY_SOURCE"
    INSUFFICIENT_INDEPENDENCE = "INSUFFICIENT_INDEPENDENCE"
    INSUFFICIENT_ENTAILMENT = "INSUFFICIENT_ENTAILMENT"
    MISSING_CAUSAL_SUPPORT = "MISSING_CAUSAL_SUPPORT"
    MISSING_MECHANISM = "MISSING_MECHANISM"
    UNRESOLVED_QUANTITATIVE_CONFLICT = "UNRESOLVED_QUANTITATIVE_CONFLICT"
    ATTRIBUTION_UNDER_SUPPORTED = "ATTRIBUTION_UNDER_SUPPORTED"
    ANALYSIS_ERROR = "ANALYSIS_ERROR"
    OTHER = "OTHER"


class LineageOriginType(StrEnum):
    ORIGINAL = "ORIGINAL"
    SYNDICATED = "SYNDICATED"
    ATTRIBUTED = "ATTRIBUTED"
    MIXED = "MIXED"
    UNKNOWN = "UNKNOWN"


class LineageResolutionMethod(StrEnum):
    DETERMINISTIC = "DETERMINISTIC"
    SEMANTIC_ASSISTED = "SEMANTIC_ASSISTED"
    UNKNOWN = "UNKNOWN"


class QualityLevel(StrEnum):
    STRONG = "STRONG"
    ADEQUATE = "ADEQUATE"
    WEAK = "WEAK"
    UNKNOWN = "UNKNOWN"


class ImpactSubtype(StrEnum):
    OBSERVED_IMPACT = "OBSERVED_IMPACT"
    REPORTED_SYMPTOM = "REPORTED_SYMPTOM"
    CAUSAL_IMPACT = "CAUSAL_IMPACT"
    LONG_TERM_IMPACT = "LONG_TERM_IMPACT"


class GapSeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    BLOCKING = "BLOCKING"


class GapStatus(StrEnum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    ACCEPTED = "ACCEPTED"


class TimePrecision(StrEnum):
    EXACT = "EXACT"
    DAY = "DAY"
    MONTH = "MONTH"
    YEAR = "YEAR"
    APPROXIMATE = "APPROXIMATE"
    UNKNOWN = "UNKNOWN"


class ReportType(StrEnum):
    FULL_INVESTIGATION = "FULL_INVESTIGATION"
    RESTRICTED_INVESTIGATION = "RESTRICTED_INVESTIGATION"
    INVESTIGATION_STATUS = "INVESTIGATION_STATUS"


class ReportReviewStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"


class ReportReleaseStatus(StrEnum):
    DRAFT = "DRAFT"
    RESTRICTED = "RESTRICTED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    PUBLISHED = "PUBLISHED"


class ReviewDecisionType(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    REQUEST_MORE_RESEARCH = "REQUEST_MORE_RESEARCH"


class AuditActorType(StrEnum):
    SYSTEM = "SYSTEM"
    HUMAN = "HUMAN"
    AGENT = "AGENT"
