"""investigation data foundation

Revision ID: 20260921_01
Revises:
Create Date: 2026-09-21 19:29:53.672566
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = "20260921_01"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

IMMUTABLE_TABLES = (
    "inv_source_snapshots",
    "inv_document_artifacts",
    "inv_evidence",
    "inv_validation_results",
    "inv_review_decisions",
    "inv_audit_events",
    "inv_recorded_tool_calls",
    "inv_recorded_model_calls",
)


def _create_immutable_guards() -> None:
    dialect = op.get_bind().dialect.name
    if dialect == "postgresql":
        op.execute(
            """
            CREATE FUNCTION inv_reject_immutable_mutation() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'investigation record is append-only';
            END;
            $$ LANGUAGE plpgsql
            """
        )
        for table in IMMUTABLE_TABLES:
            op.execute(
                f"CREATE TRIGGER trg_{table}_immutable BEFORE UPDATE OR DELETE ON {table} "
                "FOR EACH ROW EXECUTE FUNCTION inv_reject_immutable_mutation()"
            )
    elif dialect == "sqlite":
        for table in IMMUTABLE_TABLES:
            op.execute(
                f"CREATE TRIGGER trg_{table}_immutable_update BEFORE UPDATE ON {table} "
                "BEGIN SELECT RAISE(ABORT, 'investigation record is append-only'); END"
            )
            op.execute(
                f"CREATE TRIGGER trg_{table}_immutable_delete BEFORE DELETE ON {table} "
                "BEGIN SELECT RAISE(ABORT, 'investigation record is append-only'); END"
            )


def _drop_immutable_guards() -> None:
    dialect = op.get_bind().dialect.name
    if dialect == "postgresql":
        for table in IMMUTABLE_TABLES:
            op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_immutable ON {table}")
        op.execute("DROP FUNCTION IF EXISTS inv_reject_immutable_mutation()")
    elif dialect == "sqlite":
        for table in IMMUTABLE_TABLES:
            op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_immutable_update")
            op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_immutable_delete")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inv_investigations",
        sa.Column("investigation_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("event_description", sa.Text(), nullable=False),
        sa.Column("investigation_goal", sa.Text(), nullable=False),
        sa.Column(
            "scope",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("investigation_id"),
    )
    op.create_table(
        "inv_investigation_questions",
        sa.Column("question_id", sa.String(length=128), nullable=False),
        sa.Column("investigation_id", sa.String(length=128), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("is_critical", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["investigation_id"], ["inv_investigations.investigation_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("question_id"),
    )
    op.create_index(
        "ix_inv_questions_investigation_critical",
        "inv_investigation_questions",
        ["investigation_id", "is_critical"],
        unique=False,
    )
    op.create_table(
        "inv_runs",
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("investigation_id", sa.String(length=128), nullable=False),
        sa.Column(
            "mode",
            sa.Enum(
                "LIVE", "REPLAY", name="inv_run_mode", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "PENDING",
                "WAITING_FOR_EXECUTION",
                "RUNNING",
                "PAUSED",
                "INTERRUPTED",
                "BLOCKED",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="inv_run_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "current_phase",
            sa.Enum(
                "CREATED",
                "PLAN",
                "COLLECT",
                "ANALYZE",
                "VERIFY",
                "REPORT",
                "REVIEW",
                "COMPLETED",
                name="inv_workflow_phase",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("checkpoint_version", sa.Integer(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("workflow_version", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("interruption_reason", sa.Text(), nullable=True),
        sa.CheckConstraint("checkpoint_version >= 0", name="ck_inv_runs_checkpoint_nonnegative"),
        sa.CheckConstraint("state_version >= 0", name="ck_inv_runs_state_nonnegative"),
        sa.ForeignKeyConstraint(
            ["investigation_id"], ["inv_investigations.investigation_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index(
        "ix_inv_runs_investigation_status", "inv_runs", ["investigation_id", "status"], unique=False
    )
    op.create_index(
        "ix_inv_runs_phase_status", "inv_runs", ["current_phase", "status"], unique=False
    )
    op.create_table(
        "inv_sources",
        sa.Column("source_id", sa.String(length=128), nullable=False),
        sa.Column("investigation_id", sa.String(length=128), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=1000), nullable=False),
        sa.Column("publisher", sa.String(length=500), nullable=True),
        sa.Column("organization", sa.String(length=500), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum(
                "OFFICIAL_REPORT",
                "OFFICIAL_STATEMENT",
                "NEWS",
                "TECHNICAL_ANALYSIS",
                "PUBLIC_DATA",
                "WEB_PAGE",
                "PDF_REPORT",
                "OTHER",
                name="inv_source_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("is_official", sa.Boolean(), nullable=False),
        sa.Column("is_first_hand", sa.Boolean(), nullable=False),
        sa.Column("author", sa.String(length=500), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("origin_source_id", sa.String(length=128), nullable=True),
        sa.Column("syndication_cluster_id", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["investigation_id"], ["inv_investigations.investigation_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["origin_source_id"], ["inv_sources.source_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("source_id"),
        sa.UniqueConstraint("investigation_id", "canonical_url", name="uq_inv_source_url"),
    )
    op.create_index("ix_inv_sources_canonical_url", "inv_sources", ["canonical_url"], unique=False)
    op.create_index("ix_inv_sources_origin", "inv_sources", ["origin_source_id"], unique=False)
    op.create_index(
        "ix_inv_sources_syndication", "inv_sources", ["syndication_cluster_id"], unique=False
    )
    op.create_table(
        "inv_audit_events",
        sa.Column("audit_event_id", sa.String(length=128), nullable=False),
        sa.Column("investigation_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=True),
        sa.Column(
            "actor_type",
            sa.Enum(
                "SYSTEM",
                "HUMAN",
                "AGENT",
                name="inv_audit_actor_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.String(length=128), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("target_type", sa.String(length=100), nullable=False),
        sa.Column("target_id", sa.String(length=128), nullable=False),
        sa.Column("previous_state", sa.String(length=100), nullable=True),
        sa.Column("new_state", sa.String(length=100), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["investigation_id"], ["inv_investigations.investigation_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["run_id"], ["inv_runs.run_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("audit_event_id"),
    )
    op.create_index(
        "ix_inv_audit_investigation_created",
        "inv_audit_events",
        ["investigation_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_inv_audit_target", "inv_audit_events", ["target_type", "target_id"], unique=False
    )
    op.create_table(
        "inv_claims",
        sa.Column("claim_id", sa.String(length=128), nullable=False),
        sa.Column("investigation_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column(
            "claim_type",
            sa.Enum(
                "STATEMENT",
                "INSTITUTIONAL_ACTION",
                "EVENT_FACT",
                "QUANTITATIVE",
                "CAUSAL",
                "IMPACT",
                "ATTRIBUTION",
                "ANALYTIC_INFERENCE",
                name="inv_claim_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("predicate", sa.Text(), nullable=True),
        sa.Column("object", sa.Text(), nullable=True),
        sa.Column(
            "qualifiers",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "importance",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="inv_claim_importance",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("is_critical", sa.Boolean(), nullable=False),
        sa.Column(
            "validation_status",
            sa.Enum(
                "PENDING",
                "REQUIRES_RESEARCH",
                "REJECTED",
                "VERIFIED",
                "PROBABLE",
                "DISPUTED",
                "UNVERIFIED",
                name="inv_validation_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("confidence_basis", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name="ck_inv_claim_confidence",
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"], ["inv_investigations.investigation_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["run_id"], ["inv_runs.run_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("claim_id"),
    )
    op.create_index(
        "ix_inv_claims_critical_status",
        "inv_claims",
        ["is_critical", "validation_status"],
        unique=False,
    )
    op.create_index(
        "ix_inv_claims_investigation_run",
        "inv_claims",
        ["investigation_id", "run_id"],
        unique=False,
    )
    op.create_index(
        "ix_inv_claims_type_status", "inv_claims", ["claim_type", "validation_status"], unique=False
    )
    op.create_table(
        "inv_conflict_sets",
        sa.Column("conflict_id", sa.String(length=128), nullable=False),
        sa.Column("investigation_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column(
            "conflict_type",
            sa.Enum(
                "QUANTITATIVE",
                "TEMPORAL",
                "ATTRIBUTION",
                "CAUSAL",
                "SCOPE",
                "DEFINITION",
                "OTHER",
                name="inv_conflict_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                "BLOCKING",
                name="inv_conflict_severity",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "REQUIRES_RESEARCH",
                "RESOLVED",
                "ACCEPTED_UNRESOLVED",
                name="inv_conflict_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "possible_causes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("resolution_summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["investigation_id"], ["inv_investigations.investigation_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["run_id"], ["inv_runs.run_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("conflict_id"),
    )
    op.create_index(
        "ix_inv_conflicts_investigation_status",
        "inv_conflict_sets",
        ["investigation_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_inv_conflicts_run_severity", "inv_conflict_sets", ["run_id", "severity"], unique=False
    )
    op.create_table(
        "inv_execution_steps",
        sa.Column("step_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column(
            "step_type",
            sa.Enum(
                "PLANNING",
                "RESEARCH",
                "SEARCH",
                "FETCH",
                "EXTRACTION",
                "ANALYSIS",
                "VALIDATION",
                "REPORTING",
                "REVIEW",
                "OTHER",
                name="inv_step_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "agent_role",
            sa.Enum(
                "SUPERVISOR",
                "RESEARCHER",
                "ANALYST",
                "VERIFIER",
                "WRITER",
                "HARNESS",
                name="inv_agent_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "INTERRUPTED",
                "CANCELLED",
                name="inv_step_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "output_refs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("executor_instance_id", sa.String(length=128), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.CheckConstraint("attempt >= 1", name="ck_inv_steps_attempt_positive"),
        sa.ForeignKeyConstraint(["run_id"], ["inv_runs.run_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("step_id"),
        sa.UniqueConstraint("run_id", "input_fingerprint", "attempt", name="uq_inv_step_attempt"),
    )
    op.create_index(
        op.f("ix_inv_execution_steps_input_fingerprint"),
        "inv_execution_steps",
        ["input_fingerprint"],
        unique=False,
    )
    op.create_index(
        "ix_inv_steps_executor_heartbeat",
        "inv_execution_steps",
        ["executor_instance_id", "heartbeat_at"],
        unique=False,
    )
    op.create_index(
        "ix_inv_steps_run_status", "inv_execution_steps", ["run_id", "status"], unique=False
    )
    op.create_table(
        "inv_reports",
        sa.Column("report_id", sa.String(length=128), nullable=False),
        sa.Column("investigation_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "report_type",
            sa.Enum(
                "FULL_INVESTIGATION",
                "RESTRICTED_INVESTIGATION",
                "INVESTIGATION_STATUS",
                name="inv_report_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "review_status",
            sa.Enum(
                "NOT_REQUIRED",
                "PENDING",
                "APPROVED",
                "REJECTED",
                "CHANGES_REQUESTED",
                name="inv_report_review_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "release_status",
            sa.Enum(
                "DRAFT",
                "RESTRICTED",
                "REVIEW_REQUIRED",
                "PUBLISHED",
                name="inv_report_release_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("report_hash", sa.String(length=64), nullable=False),
        sa.Column("claim_set_hash", sa.String(length=64), nullable=False),
        sa.Column("release_policy_version", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("length(claim_set_hash) = 64", name="ck_inv_report_claim_set_hash"),
        sa.CheckConstraint("length(report_hash) = 64", name="ck_inv_report_hash"),
        sa.CheckConstraint("version >= 1", name="ck_inv_report_version"),
        sa.ForeignKeyConstraint(
            ["investigation_id"], ["inv_investigations.investigation_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["run_id"], ["inv_runs.run_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("report_id"),
        sa.UniqueConstraint("investigation_id", "version", name="uq_inv_report_version"),
    )
    op.create_index(
        "ix_inv_reports_claim_set_hash", "inv_reports", ["claim_set_hash"], unique=False
    )
    op.create_index("ix_inv_reports_hash", "inv_reports", ["report_hash"], unique=False)
    op.create_index(
        "ix_inv_reports_run_release", "inv_reports", ["run_id", "release_status"], unique=False
    )
    op.create_table(
        "inv_research_tasks",
        sa.Column("task_id", sa.String(length=128), nullable=False),
        sa.Column("investigation_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("target_question_id", sa.String(length=128), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="inv_research_task_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "query_hints",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("priority >= 0 AND priority <= 100", name="ck_inv_task_priority"),
        sa.ForeignKeyConstraint(
            ["investigation_id"], ["inv_investigations.investigation_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["run_id"], ["inv_runs.run_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["target_question_id"], ["inv_investigation_questions.question_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_index(
        "ix_inv_tasks_run_status_priority",
        "inv_research_tasks",
        ["run_id", "status", "priority"],
        unique=False,
    )
    op.create_table(
        "inv_source_snapshots",
        sa.Column("snapshot_id", sa.String(length=128), nullable=False),
        sa.Column("source_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_blob_ref", sa.String(length=96), nullable=False),
        sa.Column("raw_sha256", sa.String(length=64), nullable=False),
        sa.Column("cleaned_blob_ref", sa.String(length=96), nullable=True),
        sa.Column("cleaned_sha256", sa.String(length=64), nullable=True),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("encoding", sa.String(length=100), nullable=True),
        sa.Column("content_size", sa.Integer(), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column(
            "parse_status",
            sa.Enum(
                "DISCOVERED",
                "FETCHED",
                "PARSED",
                "PARTIALLY_PARSED",
                "UNSUPPORTED_MEDIA_TYPE",
                "UNSUPPORTED_SCANNED_PDF",
                "INSUFFICIENT_TEXT_LAYER",
                "EMPTY_CONTENT",
                "CORRUPT_DOCUMENT",
                "ENCRYPTED_PDF",
                "FETCH_FAILED",
                "PARSE_FAILED",
                name="inv_parse_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("parser_name", sa.String(length=100), nullable=False),
        sa.Column("parser_version", sa.String(length=100), nullable=False),
        sa.Column("normalizer_version", sa.String(length=100), nullable=False),
        sa.Column("evidence_eligible", sa.Boolean(), nullable=False),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(cleaned_blob_ref IS NULL AND cleaned_sha256 IS NULL) OR "
            "(cleaned_blob_ref LIKE 'blob://sha256/%' "
            "AND length(cleaned_sha256) = 64)",
            name="ck_inv_snapshot_cleaned_pair",
        ),
        sa.CheckConstraint(
            "raw_blob_ref LIKE 'blob://sha256/%'", name="ck_inv_snapshot_raw_blob_ref"
        ),
        sa.CheckConstraint("content_size >= 0", name="ck_inv_snapshot_size_nonnegative"),
        sa.CheckConstraint(
            "http_status IS NULL OR (http_status >= 100 AND http_status <= 599)",
            name="ck_inv_snapshot_http_status",
        ),
        sa.CheckConstraint("length(raw_sha256) = 64", name="ck_inv_snapshot_raw_hash"),
        sa.ForeignKeyConstraint(["run_id"], ["inv_runs.run_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_id"], ["inv_sources.source_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("snapshot_id"),
    )
    op.create_index(
        "ix_inv_snapshots_cleaned_blob", "inv_source_snapshots", ["cleaned_blob_ref"], unique=False
    )
    op.create_index(
        "ix_inv_snapshots_cleaned_hash", "inv_source_snapshots", ["cleaned_sha256"], unique=False
    )
    op.create_index(
        "ix_inv_snapshots_raw_blob", "inv_source_snapshots", ["raw_blob_ref"], unique=False
    )
    op.create_index(
        "ix_inv_snapshots_raw_hash", "inv_source_snapshots", ["raw_sha256"], unique=False
    )
    op.create_index("ix_inv_snapshots_run", "inv_source_snapshots", ["run_id"], unique=False)
    op.create_index(
        "ix_inv_snapshots_source_retrieved",
        "inv_source_snapshots",
        ["source_id", "retrieved_at"],
        unique=False,
    )
    op.create_table(
        "inv_timeline_events",
        sa.Column("timeline_event_id", sa.String(length=128), nullable=False),
        sa.Column("investigation_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "time_precision",
            sa.Enum(
                "EXACT",
                "DAY",
                "MONTH",
                "YEAR",
                "APPROXIMATE",
                "UNKNOWN",
                name="inv_time_precision",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "related_entity_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "validation_status",
            sa.Enum(
                "PENDING",
                "REQUIRES_RESEARCH",
                "REJECTED",
                "VERIFIED",
                "PROBABLE",
                "DISPUTED",
                "UNVERIFIED",
                name="inv_timeline_validation_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"], ["inv_investigations.investigation_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["run_id"], ["inv_runs.run_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("timeline_event_id"),
    )
    op.create_index(
        "ix_inv_timeline_investigation_time",
        "inv_timeline_events",
        ["investigation_id", "event_time"],
        unique=False,
    )
    op.create_table(
        "inv_conflict_claims",
        sa.Column("conflict_id", sa.String(length=128), nullable=False),
        sa.Column("claim_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["inv_claims.claim_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["conflict_id"], ["inv_conflict_sets.conflict_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("conflict_id", "claim_id"),
    )
    op.create_table(
        "inv_document_artifacts",
        sa.Column("artifact_id", sa.String(length=128), nullable=False),
        sa.Column("snapshot_id", sa.String(length=128), nullable=False),
        sa.Column(
            "artifact_type",
            sa.Enum(
                "HTML_NORMALIZED_TEXT",
                "PLAIN_TEXT",
                "PDF_PAGE_TEXT",
                "STRUCTURED_METADATA",
                name="inv_artifact_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("blob_ref", sa.String(length=96), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("processor_name", sa.String(length=100), nullable=False),
        sa.Column("processor_version", sa.String(length=100), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("blob_ref LIKE 'blob://sha256/%'", name="ck_inv_artifact_blob_ref"),
        sa.CheckConstraint("length(sha256) = 64", name="ck_inv_artifact_hash"),
        sa.CheckConstraint("page_number IS NULL OR page_number >= 1", name="ck_inv_artifact_page"),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["inv_source_snapshots.snapshot_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("artifact_id"),
        sa.UniqueConstraint("artifact_id", "snapshot_id", name="uq_inv_artifact_snapshot"),
    )
    op.create_index("ix_inv_artifacts_blob", "inv_document_artifacts", ["blob_ref"], unique=False)
    op.create_index("ix_inv_artifacts_hash", "inv_document_artifacts", ["sha256"], unique=False)
    op.create_index(
        "ix_inv_artifacts_snapshot_type",
        "inv_document_artifacts",
        ["snapshot_id", "artifact_type"],
        unique=False,
    )
    op.create_table(
        "inv_recorded_model_calls",
        sa.Column("call_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("step_id", sa.String(length=128), nullable=False),
        sa.Column("operation", sa.String(length=200), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("request_blob_ref", sa.String(length=96), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_blob_ref", sa.String(length=96), nullable=False),
        sa.Column("response_hash", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=200), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("schema_version", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=100), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "request_blob_ref LIKE 'blob://sha256/%'", name="ck_inv_model_request_blob"
        ),
        sa.CheckConstraint(
            "response_blob_ref LIKE 'blob://sha256/%'", name="ck_inv_model_response_blob"
        ),
        sa.CheckConstraint("length(request_hash) = 64", name="ck_inv_model_request_hash"),
        sa.CheckConstraint("length(response_hash) = 64", name="ck_inv_model_response_hash"),
        sa.ForeignKeyConstraint(["run_id"], ["inv_runs.run_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["step_id"], ["inv_execution_steps.step_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("call_id"),
        sa.UniqueConstraint(
            "run_id", "operation", "request_fingerprint", name="uq_inv_model_call_fingerprint"
        ),
    )
    op.create_index(
        "ix_inv_model_calls_fingerprint",
        "inv_recorded_model_calls",
        ["request_fingerprint"],
        unique=False,
    )
    op.create_index(
        "ix_inv_model_calls_request_blob",
        "inv_recorded_model_calls",
        ["request_blob_ref"],
        unique=False,
    )
    op.create_index(
        "ix_inv_model_calls_request_hash",
        "inv_recorded_model_calls",
        ["request_hash"],
        unique=False,
    )
    op.create_index(
        "ix_inv_model_calls_response_blob",
        "inv_recorded_model_calls",
        ["response_blob_ref"],
        unique=False,
    )
    op.create_index(
        "ix_inv_model_calls_response_hash",
        "inv_recorded_model_calls",
        ["response_hash"],
        unique=False,
    )
    op.create_index(
        "ix_inv_model_calls_step", "inv_recorded_model_calls", ["step_id"], unique=False
    )
    op.create_table(
        "inv_recorded_tool_calls",
        sa.Column("call_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("step_id", sa.String(length=128), nullable=False),
        sa.Column("operation", sa.String(length=200), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("request_blob_ref", sa.String(length=96), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_blob_ref", sa.String(length=96), nullable=False),
        sa.Column("response_hash", sa.String(length=64), nullable=False),
        sa.Column("tool_name", sa.String(length=200), nullable=False),
        sa.Column("provider", sa.String(length=200), nullable=False),
        sa.Column("schema_version", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=100), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "request_blob_ref LIKE 'blob://sha256/%'", name="ck_inv_tool_request_blob"
        ),
        sa.CheckConstraint(
            "response_blob_ref LIKE 'blob://sha256/%'", name="ck_inv_tool_response_blob"
        ),
        sa.CheckConstraint("length(request_hash) = 64", name="ck_inv_tool_request_hash"),
        sa.CheckConstraint("length(response_hash) = 64", name="ck_inv_tool_response_hash"),
        sa.ForeignKeyConstraint(["run_id"], ["inv_runs.run_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["step_id"], ["inv_execution_steps.step_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("call_id"),
        sa.UniqueConstraint(
            "run_id", "operation", "request_fingerprint", name="uq_inv_tool_call_fingerprint"
        ),
    )
    op.create_index(
        "ix_inv_tool_calls_fingerprint",
        "inv_recorded_tool_calls",
        ["request_fingerprint"],
        unique=False,
    )
    op.create_index(
        "ix_inv_tool_calls_request_blob",
        "inv_recorded_tool_calls",
        ["request_blob_ref"],
        unique=False,
    )
    op.create_index(
        "ix_inv_tool_calls_request_hash",
        "inv_recorded_tool_calls",
        ["request_hash"],
        unique=False,
    )
    op.create_index(
        "ix_inv_tool_calls_response_blob",
        "inv_recorded_tool_calls",
        ["response_blob_ref"],
        unique=False,
    )
    op.create_index(
        "ix_inv_tool_calls_response_hash",
        "inv_recorded_tool_calls",
        ["response_hash"],
        unique=False,
    )
    op.create_index("ix_inv_tool_calls_step", "inv_recorded_tool_calls", ["step_id"], unique=False)
    op.create_table(
        "inv_report_sections",
        sa.Column("section_id", sa.String(length=128), nullable=False),
        sa.Column("report_id", sa.String(length=128), nullable=False),
        sa.Column("section_type", sa.String(length=100), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("content_blob_ref", sa.String(length=96), nullable=True),
        sa.Column(
            "structured_content",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "content_blob_ref IS NULL OR content_blob_ref LIKE 'blob://sha256/%'",
            name="ck_inv_report_section_blob_ref",
        ),
        sa.CheckConstraint(
            "content_blob_ref IS NOT NULL OR structured_content IS NOT NULL",
            name="ck_inv_report_section_content",
        ),
        sa.CheckConstraint("order_index >= 0", name="ck_inv_report_section_order"),
        sa.ForeignKeyConstraint(["report_id"], ["inv_reports.report_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("section_id"),
        sa.UniqueConstraint("report_id", "order_index", name="uq_inv_report_section_order"),
    )
    op.create_index(
        "ix_inv_report_sections_blob", "inv_report_sections", ["content_blob_ref"], unique=False
    )
    op.create_index(
        "ix_inv_report_sections_report_type",
        "inv_report_sections",
        ["report_id", "section_type"],
        unique=False,
    )
    op.create_table(
        "inv_research_gaps",
        sa.Column("gap_id", sa.String(length=128), nullable=False),
        sa.Column("investigation_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column(
            "gap_type",
            sa.Enum(
                "EVIDENCE_GAP",
                "UNREADABLE_SOURCE",
                "SOURCE_CONFLICT",
                "MISSING_PRIMARY_SOURCE",
                "INSUFFICIENT_INDEPENDENCE",
                "ANALYSIS_ERROR",
                "OTHER",
                name="inv_gap_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("target_question_id", sa.String(length=128), nullable=True),
        sa.Column("target_claim_id", sa.String(length=128), nullable=True),
        sa.Column("source_id", sa.String(length=128), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                "BLOCKING",
                name="inv_gap_severity",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "IN_PROGRESS",
                "RESOLVED",
                "ACCEPTED",
                name="inv_gap_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "suggested_actions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["investigation_id"], ["inv_investigations.investigation_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["run_id"], ["inv_runs.run_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_id"], ["inv_sources.source_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["target_claim_id"], ["inv_claims.claim_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["target_question_id"], ["inv_investigation_questions.question_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("gap_id"),
    )
    op.create_index(
        "ix_inv_gaps_investigation_severity",
        "inv_research_gaps",
        ["investigation_id", "severity"],
        unique=False,
    )
    op.create_index(
        "ix_inv_gaps_run_status", "inv_research_gaps", ["run_id", "status"], unique=False
    )
    op.create_table(
        "inv_review_decisions",
        sa.Column("review_id", sa.String(length=128), nullable=False),
        sa.Column("report_id", sa.String(length=128), nullable=False),
        sa.Column("reviewer_id", sa.String(length=128), nullable=False),
        sa.Column(
            "decision",
            sa.Enum(
                "APPROVE",
                "REJECT",
                "REQUEST_MORE_RESEARCH",
                name="inv_review_decision",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("report_version", sa.Integer(), nullable=False),
        sa.Column("report_hash", sa.String(length=64), nullable=False),
        sa.Column("claim_set_hash", sa.String(length=64), nullable=False),
        sa.Column("release_policy_version", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("length(claim_set_hash) = 64", name="ck_inv_review_claim_set_hash"),
        sa.CheckConstraint("length(report_hash) = 64", name="ck_inv_review_report_hash"),
        sa.CheckConstraint("report_version >= 1", name="ck_inv_review_report_version"),
        sa.ForeignKeyConstraint(["report_id"], ["inv_reports.report_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("review_id"),
    )
    op.create_index(
        "ix_inv_reviews_report_created",
        "inv_review_decisions",
        ["report_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "inv_validation_results",
        sa.Column("validation_id", sa.String(length=128), nullable=False),
        sa.Column("claim_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column(
            "claim_type",
            sa.Enum(
                "STATEMENT",
                "INSTITUTIONAL_ACTION",
                "EVENT_FACT",
                "QUANTITATIVE",
                "CAUSAL",
                "IMPACT",
                "ATTRIBUTION",
                "ANALYTIC_INFERENCE",
                name="inv_validation_claim_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("profile_version", sa.String(length=100), nullable=False),
        sa.Column("citation_valid", sa.Boolean(), nullable=False),
        sa.Column(
            "entailment_result",
            sa.Enum(
                "PENDING",
                "ENTAILED",
                "NOT_ENTAILED",
                "CONTRADICTED",
                "UNCERTAIN",
                name="inv_validation_entailment",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("independent_source_count", sa.Integer(), nullable=False),
        sa.Column("strong_contradiction", sa.Boolean(), nullable=False),
        sa.Column(
            "source_quality_summary",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("sufficiency_result", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "REQUIRES_RESEARCH",
                "REJECTED",
                "VERIFIED",
                "PROBABLE",
                "DISPUTED",
                "UNVERIFIED",
                name="inv_validation_result_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("validation_basis", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_inv_validation_confidence"
        ),
        sa.CheckConstraint("independent_source_count >= 0", name="ck_inv_validation_independence"),
        sa.ForeignKeyConstraint(["claim_id"], ["inv_claims.claim_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["run_id"], ["inv_runs.run_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("validation_id"),
    )
    op.create_index(
        "ix_inv_validation_claim_created",
        "inv_validation_results",
        ["claim_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_inv_validation_run_status", "inv_validation_results", ["run_id", "status"], unique=False
    )
    op.create_table(
        "inv_evidence",
        sa.Column("evidence_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("snapshot_id", sa.String(length=128), nullable=False),
        sa.Column("artifact_id", sa.String(length=128), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "locator_type",
            sa.Enum(
                "TEXT_RANGE",
                "PDF_TEXT_RANGE",
                name="inv_locator_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "locator_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("extractor_name", sa.String(length=100), nullable=False),
        sa.Column("extractor_version", sa.String(length=100), nullable=False),
        sa.CheckConstraint("length(content_hash) = 64", name="ck_inv_evidence_content_hash"),
        sa.ForeignKeyConstraint(
            ["artifact_id", "snapshot_id"],
            ["inv_document_artifacts.artifact_id", "inv_document_artifacts.snapshot_id"],
            name="fk_inv_evidence_artifact_snapshot",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["run_id"], ["inv_runs.run_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["inv_source_snapshots.snapshot_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("evidence_id"),
    )
    op.create_index("ix_inv_evidence_artifact", "inv_evidence", ["artifact_id"], unique=False)
    op.create_index("ix_inv_evidence_content_hash", "inv_evidence", ["content_hash"], unique=False)
    op.create_index("ix_inv_evidence_run", "inv_evidence", ["run_id"], unique=False)
    op.create_index("ix_inv_evidence_snapshot", "inv_evidence", ["snapshot_id"], unique=False)
    op.create_table(
        "inv_report_section_claims",
        sa.Column("section_id", sa.String(length=128), nullable=False),
        sa.Column("claim_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["inv_claims.claim_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["section_id"], ["inv_report_sections.section_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("section_id", "claim_id"),
    )
    op.create_table(
        "inv_claim_evidence_relations",
        sa.Column("relation_id", sa.String(length=128), nullable=False),
        sa.Column("claim_id", sa.String(length=128), nullable=False),
        sa.Column("evidence_id", sa.String(length=128), nullable=False),
        sa.Column(
            "stance",
            sa.Enum(
                "SUPPORTS",
                "CONTRADICTS",
                "CONTEXT",
                name="inv_relation_stance",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "entailment_status",
            sa.Enum(
                "PENDING",
                "ENTAILED",
                "NOT_ENTAILED",
                "CONTRADICTED",
                "UNCERTAIN",
                name="inv_entailment_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("entailment_score", sa.Float(), nullable=True),
        sa.Column("semantic_judgment_ref", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "entailment_score IS NULL OR (entailment_score >= 0 AND entailment_score <= 1)",
            name="ck_inv_relation_entailment_score",
        ),
        sa.ForeignKeyConstraint(["claim_id"], ["inv_claims.claim_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["evidence_id"], ["inv_evidence.evidence_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("relation_id"),
        sa.UniqueConstraint("claim_id", "evidence_id", name="uq_inv_claim_evidence_pair"),
    )
    op.create_index(
        "ix_inv_relations_claim_stance",
        "inv_claim_evidence_relations",
        ["claim_id", "stance"],
        unique=False,
    )
    op.create_index(
        "ix_inv_relations_evidence", "inv_claim_evidence_relations", ["evidence_id"], unique=False
    )
    op.create_table(
        "inv_timeline_evidence",
        sa.Column("timeline_event_id", sa.String(length=128), nullable=False),
        sa.Column("evidence_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(["evidence_id"], ["inv_evidence.evidence_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["timeline_event_id"], ["inv_timeline_events.timeline_event_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("timeline_event_id", "evidence_id"),
    )
    _create_immutable_guards()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_immutable_guards()
    op.drop_table("inv_timeline_evidence")
    op.drop_index("ix_inv_relations_evidence", table_name="inv_claim_evidence_relations")
    op.drop_index("ix_inv_relations_claim_stance", table_name="inv_claim_evidence_relations")
    op.drop_table("inv_claim_evidence_relations")
    op.drop_table("inv_report_section_claims")
    op.drop_index("ix_inv_evidence_snapshot", table_name="inv_evidence")
    op.drop_index("ix_inv_evidence_run", table_name="inv_evidence")
    op.drop_index("ix_inv_evidence_content_hash", table_name="inv_evidence")
    op.drop_index("ix_inv_evidence_artifact", table_name="inv_evidence")
    op.drop_table("inv_evidence")
    op.drop_index("ix_inv_validation_run_status", table_name="inv_validation_results")
    op.drop_index("ix_inv_validation_claim_created", table_name="inv_validation_results")
    op.drop_table("inv_validation_results")
    op.drop_index("ix_inv_reviews_report_created", table_name="inv_review_decisions")
    op.drop_table("inv_review_decisions")
    op.drop_index("ix_inv_gaps_run_status", table_name="inv_research_gaps")
    op.drop_index("ix_inv_gaps_investigation_severity", table_name="inv_research_gaps")
    op.drop_table("inv_research_gaps")
    op.drop_index("ix_inv_report_sections_report_type", table_name="inv_report_sections")
    op.drop_index("ix_inv_report_sections_blob", table_name="inv_report_sections")
    op.drop_table("inv_report_sections")
    op.drop_index("ix_inv_tool_calls_step", table_name="inv_recorded_tool_calls")
    op.drop_index("ix_inv_tool_calls_response_hash", table_name="inv_recorded_tool_calls")
    op.drop_index("ix_inv_tool_calls_response_blob", table_name="inv_recorded_tool_calls")
    op.drop_index("ix_inv_tool_calls_request_hash", table_name="inv_recorded_tool_calls")
    op.drop_index("ix_inv_tool_calls_request_blob", table_name="inv_recorded_tool_calls")
    op.drop_index("ix_inv_tool_calls_fingerprint", table_name="inv_recorded_tool_calls")
    op.drop_table("inv_recorded_tool_calls")
    op.drop_index("ix_inv_model_calls_step", table_name="inv_recorded_model_calls")
    op.drop_index("ix_inv_model_calls_response_hash", table_name="inv_recorded_model_calls")
    op.drop_index("ix_inv_model_calls_response_blob", table_name="inv_recorded_model_calls")
    op.drop_index("ix_inv_model_calls_request_hash", table_name="inv_recorded_model_calls")
    op.drop_index("ix_inv_model_calls_request_blob", table_name="inv_recorded_model_calls")
    op.drop_index("ix_inv_model_calls_fingerprint", table_name="inv_recorded_model_calls")
    op.drop_table("inv_recorded_model_calls")
    op.drop_index("ix_inv_artifacts_snapshot_type", table_name="inv_document_artifacts")
    op.drop_index("ix_inv_artifacts_hash", table_name="inv_document_artifacts")
    op.drop_index("ix_inv_artifacts_blob", table_name="inv_document_artifacts")
    op.drop_table("inv_document_artifacts")
    op.drop_table("inv_conflict_claims")
    op.drop_index("ix_inv_timeline_investigation_time", table_name="inv_timeline_events")
    op.drop_table("inv_timeline_events")
    op.drop_index("ix_inv_snapshots_source_retrieved", table_name="inv_source_snapshots")
    op.drop_index("ix_inv_snapshots_run", table_name="inv_source_snapshots")
    op.drop_index("ix_inv_snapshots_raw_hash", table_name="inv_source_snapshots")
    op.drop_index("ix_inv_snapshots_raw_blob", table_name="inv_source_snapshots")
    op.drop_index("ix_inv_snapshots_cleaned_hash", table_name="inv_source_snapshots")
    op.drop_index("ix_inv_snapshots_cleaned_blob", table_name="inv_source_snapshots")
    op.drop_table("inv_source_snapshots")
    op.drop_index("ix_inv_tasks_run_status_priority", table_name="inv_research_tasks")
    op.drop_table("inv_research_tasks")
    op.drop_index("ix_inv_reports_run_release", table_name="inv_reports")
    op.drop_index("ix_inv_reports_hash", table_name="inv_reports")
    op.drop_index("ix_inv_reports_claim_set_hash", table_name="inv_reports")
    op.drop_table("inv_reports")
    op.drop_index("ix_inv_steps_run_status", table_name="inv_execution_steps")
    op.drop_index("ix_inv_steps_executor_heartbeat", table_name="inv_execution_steps")
    op.drop_index(
        op.f("ix_inv_execution_steps_input_fingerprint"), table_name="inv_execution_steps"
    )
    op.drop_table("inv_execution_steps")
    op.drop_index("ix_inv_conflicts_run_severity", table_name="inv_conflict_sets")
    op.drop_index("ix_inv_conflicts_investigation_status", table_name="inv_conflict_sets")
    op.drop_table("inv_conflict_sets")
    op.drop_index("ix_inv_claims_type_status", table_name="inv_claims")
    op.drop_index("ix_inv_claims_investigation_run", table_name="inv_claims")
    op.drop_index("ix_inv_claims_critical_status", table_name="inv_claims")
    op.drop_table("inv_claims")
    op.drop_index("ix_inv_audit_target", table_name="inv_audit_events")
    op.drop_index("ix_inv_audit_investigation_created", table_name="inv_audit_events")
    op.drop_table("inv_audit_events")
    op.drop_index("ix_inv_sources_syndication", table_name="inv_sources")
    op.drop_index("ix_inv_sources_origin", table_name="inv_sources")
    op.drop_index("ix_inv_sources_canonical_url", table_name="inv_sources")
    op.drop_table("inv_sources")
    op.drop_index("ix_inv_runs_phase_status", table_name="inv_runs")
    op.drop_index("ix_inv_runs_investigation_status", table_name="inv_runs")
    op.drop_table("inv_runs")
    op.drop_index(
        "ix_inv_questions_investigation_critical", table_name="inv_investigation_questions"
    )
    op.drop_table("inv_investigation_questions")
    op.drop_table("inv_investigations")
    # ### end Alembic commands ###
